#baseURL = "https://master.d1qkinvelrebw8.amplifyapp.com/"
languageCode = "en-us"
title = "The Bone Yard"
theme = "bastard"

[params]
    # Short subtitle/tagline. This is displayed in the header.
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
    # To load additional CSS styles
    customCSS = ['hamburg.css']
    # Show this very user-friendly and absolutely not annoying GDPR notice at the bottom of the page
    ShowGDPRNotice = true
	subtitle = "The unoffical Bone Yard web page "
	# Since 0.57.0 there's the concept of "main sections". The files for the section "posts" are in "./content/posts/".
	mainSections = ["Builders"]

    name = "The Bone Yard"
    #description = "A mystery person"
    #email = "anthony.russel42@example.com"
    #phone = "+234 23 9873237"
    #address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017
    #avatar = "images/guy.jpg"
    banner = "images/bg.png"
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true


[menu]
[[menu.main]]
				name = "Builders"
				identifier = "Builders"
				URL = "/builders/builders"
				weight = 2
[[menu.main]]
				name = "Features"
				identifier = "Features"
				URL = "/features/features"
				weight = 3
[[menu.main]]
				name = "Events"
				identifier = "Events"
				URL = "/pages/events"
				weight = 10
[[menu.main]]
				name = "Photos"
				identifier = "Photos"
				URL = "/pages/photos"
				weight =7
[[menu.main]]
				name = "Video"
				identifier = "Video"
				URL = "/pages/video"
				weight =8

[[menu.main]]
                name = "About"
                identifier = "About"
                URL = "/pages/About"
                weight =1
